"""empty message

Revision ID: 0483245e6801
Revises: 
Create Date: 2021-02-17 18:03:02.877874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0483245e6801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('quotes')
    op.add_column('customer', sa.Column('DOB', sa.DateTime(), nullable=False))
    op.add_column('customer', sa.Column('allergies', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('medicines', sa.String(length=255), nullable=True))
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.drop_column('order', 'payment_id')
    op.add_column('product', sa.Column('image', sa.String(length=300), nullable=True))
    op.drop_index('uwi_id', table_name='user')
    op.drop_column('user', 'uwi_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uwi_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('uwi_id', 'user', ['uwi_id'], unique=True)
    op.drop_column('product', 'image')
    op.add_column('order', sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('order_ibfk_3', 'order', 'payment', ['payment_id'], ['id'])
    op.drop_column('customer', 'medicines')
    op.drop_column('customer', 'allergies')
    op.drop_column('customer', 'DOB')
    op.create_table('quotes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('quote', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('quote_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('added_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('pharmacy')
    # ### end Alembic commands ###
