"""empty message

Revision ID: 0d9ad31c9311
Revises: cc4bbf79dcbe
Create Date: 2021-04-14 10:47:14.083763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9ad31c9311'
down_revision = 'cc4bbf79dcbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
