"""empty message

Revision ID: 3a5295ff893d
Revises: 
Create Date: 2021-04-13 22:02:55.390394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5295ff893d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('date_paid', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prescription_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=300), nullable=False),
    sa.Column('supplier_cost_price', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('QoH', sa.Integer(), nullable=False),
    sa.Column('stock_unit', sa.Integer(), nullable=False),
    sa.Column('unit_retail_price', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('total_retail_price', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('allergies', sa.String(length=255), nullable=True),
    sa.Column('medicines', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('order_total', sa.Float(decimal_return_scale=2), nullable=False),
    sa.Column('date_placed', sa.DateTime(), nullable=False),
    sa.Column('pickup_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('prescription_order')
    op.drop_table('pharmacy')
    op.drop_table('payment')
    # ### end Alembic commands ###
