"""empty message

Revision ID: cc4bbf79dcbe
Revises: 3a5295ff893d
Create Date: 2021-04-14 10:28:48.441430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4bbf79dcbe'
down_revision = '3a5295ff893d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
